# Generated by Django 4.2.6 on 2023-11-06 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eflo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_listing',
            new_name='JobListing',
        ),
        migrations.RenameModel(
            old_name='log_message',
            new_name='LogMessage',
        ),
    ]
