# Generated by Django 4.2.6 on 2023-11-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eflo', '0002_rename_job_listing_joblisting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kword', models.CharField(max_length=100)),
                ('kword_link', models.CharField(max_length=300)),
            ],
        ),
    ]
